application: kanjihub
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static

- url: /static/(.*)
  static_dir: static/\1

- url: /api/.*
  script: _go_app

- url: /populate
  script: _go_app
  login: admin

- url: /
  script: _go_app

- url: /.*
  script: _go_app
